### ISSUE TITLE
Style PNGs are occasionally bugged

### ISSUE THREAD

**Issue by UntotenTheo** [wafflethings/RankTitleSwapper#3]
this issue is likely caused by the **LAYER 7: VIOLENCE** update released recently, but style ranks appear to break and fall back to the original image on certain levels, and then all style ranks are moved up a bunch

known bugged levels:
0-2: THE MEATGRINDER
Sandbox
(MODDED) Divine Delivery

Example of bugged Style Rank below
![image](https://github.com/wafflethings/RankTitleSwapper/assets/75056493/3580577a-1b5d-47e4-aac9-0f16873e3ccd)

**Comment by wafflethings** [comment]
ultrakill issue :3  i blame hakita
